# Generated by Django 6.0.3 on 2026-03-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_alter_bet_amount_alter_userprofile_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='odds',
        ),
    ]
