# Generated by Django 6.0.3 on 2026-03-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_remove_option_odds'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='initial_liquidity',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
